### ISSUE TITLE
Uncaught TypeError: Cannot read property 'minimapForEditor' of null

### ISSUE THREAD

**Issue by rugk** [T-800/atom-minimap-hide#3]
[Enter steps to reproduce below:]
1. Try to switch between a tab after you have just disabled the extension. :confused: 

**Atom Version**: 1.0.7
**System**: **\* (corrected: Windows 7)
**Thrown From**: [minimap-hide](https://github.com/T-800/atom-minimap-hide) package, v0.3.0
### Stack Trace

Uncaught TypeError: Cannot read property 'minimapForEditor' of null

```
At C:\Users\%username%\.atom\packages\minimap-hide\lib\minimap-hide.coffee:40

TypeError: Cannot read property 'minimapForEditor' of null
  at Object.module.exports.show (C:\Users\%username%\.atom\packages\minimap-hide\lib\minimap-hide.coffee:40:49)
  at C:\Users\%username%\.atom\packages\minimap-hide\lib\minimap-hide.coffee:29:8
  at Emitter.module.exports.Emitter.emit (C:\Users\%username%\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at C:\Users\%username%\AppData\Local\atom\app-1.0.7\resources\app.asar\src\pane-container.js:320:34
  at Emitter.module.exports.Emitter.emit (C:\Users\%username%\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (C:\Users\%username%\AppData\Local\atom\app-1.0.7\resources\app.asar\src\pane.js:242:22)
  at Pane.module.exports.Pane.activateItem (C:\Users\%username%\AppData\Local\atom\app-1.0.7\resources\app.asar\src\pane.js:306:21)
  at tabs-tab.<anonymous> (C:\Users\%username%\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:210:24)
  at space-pen-ul.jQuery.event.dispatch (C:\Users\%username%\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at space-pen-ul.elemData.handle (C:\Users\%username%\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```
### Commands

```
     -0:43.5.0 editor-stats:toggle (atom-workspace.workspace.scrollbars-visible-always)
     -0:34.7.0 settings-view:open (atom-text-editor.editor.is-focused)
  3x -0:27.8.0 core:move-left (atom-text-editor.editor.mini.is-focused)
     -0:26.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "projectHome": "D:\\Users\\%username%\\GitHub",
    "disabledPackages": [
      "metrics",
      "autocomplete-php",
      "autocomplete-emojis",
      "atom-php-navigation",
      "minimap-autohide",
      "minimap-hide",
      "minimap-selection"
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
aligner-php, v1.0.0
autohide-tree-view, v0.24.0
color-picker, v2.0.11
editor-stats, v0.17.0
file-icons, v1.6.6
keyboard-localization, v1.4.7
language-autoit, v0.2.1
language-batch, v0.3.3
minimap, v4.13.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.0
minimap-linter, v1.0.0
php-analyser, v0.2.0

# Dev
No dev packages
```

**Comment by rugk** [comment]
[Enter steps to reproduce below:]
1. After I disabled this package it showed this error.

**Atom Version**: 1.1.0
**System**: Windows 7
**Thrown From**: [atom-dark-syntax](https://github.com/atom/atom-dark-syntax) package, v0.27.0

### Stack Trace

Uncaught TypeError: Cannot read property 'minimapForEditor' of null

```
At /D:/Users/%username%/.atom/packages/minimap-hide/lib/minimap-hide.coffee:55

TypeError: Cannot read property 'minimapForEditor' of null
  at Object.module.exports.show (D:\Users\%username%\.atom\packages\minimap-hide\lib\minimap-hide.coffee:40:49)
  at D:\Users\%username%\.atom\packages\minimap-hide\lib\minimap-hide.coffee:29:8
  at Emitter.module.exports.Emitter.emit (C:\Users\%username%\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
  at C:\Users\%username%\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane-container.js:333:27
  at Pane.module.exports.Pane.observeActiveItem (C:\Users\%username%\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane.js:195:7)
  at C:\Users\%username%\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane-container.js:331:42
  at Emitter.module.exports.Emitter.emit (C:\Users\%username%\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
  at PaneContainer.module.exports.PaneContainer.setActivePane (C:\Users\%username%\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane-container.js:196:22)
  at Pane.module.exports.Pane.activate (C:\Users\%username%\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane.js:616:15)
  at Pane.module.exports.Pane.focus (C:\Users\%username%\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane.js:206:21)
  at atom-pane.<anonymous> (C:\Users\%username%\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane-element.js:50:23)

```

### Commands

```
     -6:57.2.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -6:57.2.0 core:cancel (atom-text-editor.editor.is-focused)
     -6:56.6.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -6:56.6.0 core:cancel (atom-text-editor.editor.is-focused)
     -6:54.5.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -6:54.5.0 core:cancel (atom-text-editor.editor.is-focused)
     -6:52.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -6:52.3.0 core:cancel (atom-text-editor.editor.is-focused)
     -6:51 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -6:51 core:cancel (atom-text-editor.editor.is-focused)
     -4:50.4.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-atom-dark-ui)
     -2:46.4.0 command-palette:toggle (ul.list-inline.tab-bar.inset-panel)
     -2:43.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -2:42.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 13x -2:42.3.0 markdown-preview:toggle (ul.list-inline.tab-bar.inset-panel)
     -1:38.9.0 release-notes:show (atom-text-editor.editor.mini.is-focused)
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "autocomplete-emojis",
      "metrics",
      "package-cop",
      "tree-view-breadcrumb",
      "foldername-tabs",
      "markdown-table-formatter",
      "minimap-hide",
      "minimap-codeglance"
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
[...]
minimap, v4.16.0
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.3.2
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-linter, v1.0.0
minimap-pigments, v0.1.7
minimap-selection, v4.3.1
[...]

# Dev
No dev packages
```

**Comment by ShadowLNC** [comment]
Bump; this issue is unfixed and just occurred for me.

Occurs on package disable.

**Atom Version**: 1.8.0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [minimap-hide](https://github.com/T-800/atom-minimap-hide) package, v0.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'minimapForEditor' of null

```
At /C:/Users/Scott/.atom/packages/minimap-hide/lib/minimap-hide.coffee:55

TypeError: Cannot read property 'minimapForEditor' of null
    at Object.module.exports.show (file:///C:/Users/Scott/.atom/packages/minimap-hide/lib/minimap-hide.coffee:40:49)
    at file:///C:/Users/Scott/.atom/packages/minimap-hide/lib/minimap-hide.coffee:29:8
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Scott\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Scott\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at C:\Users\Scott\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane-container.js:346:27
    at Pane.module.exports.Pane.observeActiveItem (C:\Users\Scott\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:223:7)
    at C:\Users\Scott\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane-container.js:344:42
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Scott\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Scott\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at PaneContainer.module.exports.PaneContainer.setActivePane (C:\Users\Scott\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane-container.js:196:22)
    at Pane.module.exports.Pane.activate (C:\Users\Scott\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:807:15)
    at Pane.module.exports.Pane.focus (C:\Users\Scott\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:234:21)
    at atom-pane.<anonymous> (C:\Users\Scott\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane-element.js:50:23)
```

### Commands

```
     -2:21.7.0 minimap:toggle-minimap-autohide (atom-text-editor.editor.power-mode)
     -2:10.9.0 command-palette:toggle (atom-text-editor.editor.power-mode.is-focused)
     -1:59.7.0 core:select-up (atom-text-editor.editor.mini.is-focused)
     -1:58.8.0 core:move-right (atom-text-editor.editor.mini.is-focused)
     -1:57.4.0 core:select-up (atom-text-editor.editor.mini.is-focused)
     -1:56.5.0 core:copy (atom-text-editor.editor.mini.is-focused)
     -1:54.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:54.5.0 minimap:toggle-minimap-autohide (atom-text-editor.editor.power-mode)
     -1:51.7.0 core:paste (atom-text-editor.editor.power-mode.is-focused)
     -1:51.5.0 editor:newline (atom-text-editor.editor.power-mode.is-focused)
  3x -1:48.9.0 core:undo (atom-text-editor.editor.power-mode.is-focused)
     -1:41.1.0 window:reset-font-size (atom-text-editor.editor.power-mode.is-focused)
     -1:11.4.0 command-palette:toggle (atom-text-editor.editor.power-mode.is-focused)
     -1:10.1.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -1:06.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:06.7.0 minimap:toggle-minimap-autohide (atom-text-editor.editor.power-mode)
```

### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "autoclose-html",
      "minimap-hide"
    ],
    "packagesWithKeymapsDisabled": [
      "bookmarks",
      "activate-power-mode"
    ],
    "projectHome": "D:\\Professional\\importrandom",
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
activate-power-mode, v0.5.2
build, v0.64.0
busy, v0.5.0
django-atom, v0.2.4
minimap, v4.24.6
minimap-autohide, v0.10.1
minimap-bookmarks, v0.3.1
minimap-cursorline, v0.2.0
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.1
minimap-highlight-selected, v4.4.0
minimap-selection, v4.4.0
minimap-split-diff, v0.3.1
script, v3.7.3

# Dev
No dev packages
```

**Comment by mdotwills** [comment]
Same issue here. I suspect the tab is trying to call the plug in after it has been removed. I don't know the internals of atom atm, but can the hook in the page be updated to remove the call to the autohide plugin on plugin remove?
